
# +JUNTOS
# Ficheiro: apps/mobile/Makefile
# Descrição: Comandos de conveniência para o desenvolvimento Flutter
# Autor: (+JUNTOS team)
# Locale: pt_PT

.PHONY: get gen watch

get:
	flutter pub get

gen:
	flutter pub run build_runner build --delete-conflicting-outputs

watch:
	flutter pub run build_runner watch --delete-conflicting-outputs
