
# +JUNTOS
# Ficheiro: backend/service-core/src/main/resources/application.yml
# Descrição: Configuração principal da aplicação
# Autor: (+JUNTOS team)
# Locale: pt_PT

spring:
  application:
    name: service-core

---

spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/juntos_dev
    username: user
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/juntos_dev

---

spring:
  config:
    activate:
      on-profile: stg
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  flyway:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

---

spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  flyway:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
